Patch 1
krisfoster/ni-k8s-demo pull request #3
Opened 2022-06-07 06:52 UTC by sachin-pikle

These are the changes I did while testing. Thank you!

2022-06-23 09:36 UTC, krisfoster approved these changes

2022-06-23 09:52 UTC, krisfoster requested changes
Thanks for reviewing this and picking up things that needed to be changed. Can I check why the docker pushes for the transform app are commented out? I'd like to keep those in and also the stress test jobs for the graalee version of the apps. The move to using distroless for the transform app was a very good catch.

2022-06-23 09:55 UTC, krisfoster reviewed
I'd like to keep the transform app set up in this, thanks

2022-06-30 08:20 UTC, sachin-pikle commented
>> I'd like to keep ... the stress test jobs for the graalee version of the apps.

Since we were comparing OpenJDK with Native Image, I commented the graalee version. I will uncomment it.

2022-06-30 08:32 UTC, merged